
name: 'belvo_challenge'
version: '1.0.0'
config-version: 2

profile: 'showcase'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:   
  - "target"
  - "dbt_packages"

models:
  belvo_challenge:
    staging:
      materialized: view
      +schema : "staging_showcase"
    reporting:
      +materialized: table
      +schema: "showcase"
